version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gradle]"
      include: "scope"
    labels:
      - "dependencies"   
    target-branch: "dev"
  
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"  
    labels:
      - "dependencies"   
    target-branch: "dev"
  
