name: Test all JDKs on all OSes and Publish

on: [push, pull_request]

permissions: write-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: "🧪 Test"
    strategy:
      fail-fast: false
      matrix:
        java_version: [11, 17, 18] # Test all LTS releases and the latest one
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java_version }}
      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup and Run Gradle
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: test
  coverage:
    runs-on: ubuntu-latest
    needs:
      - test
    name: "📄 Codecov Report"
    strategy:
      matrix:
        test-type: [unit, integration]
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup and Run Gradle
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: ${{ matrix.test-type }}TestsCoverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          flags: "${{ matrix.test-type }}Tests"
          verbose: true
          token: "${{ secrets.CODECOV_TOKEN }}"
  publish:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.repository == 'javalin/javalin-ssl'
    needs:
      - test
    name: "🛫 Publish to maven repo"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate version
        uses: HardNorth/github-version-generate@v1.1.2
        with:
          version-source: file
          version-file: build.gradle
          version-file-extraction-pattern: '(?<=version\s*=\s*'')\S+(?='')'

      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup and Run Gradle
        uses: gradle/gradle-build-action@v2.2.1
        env:
          MAVEN_NAME: '${{ secrets.MAVEN_NAME }}'
          MAVEN_TOKEN: '${{ secrets.MAVEN_TOKEN }}'
        with:
          arguments: publish

      - name: Create Pre-Release
        if: contains(env.CURRENT_VERSION, 'SNAPSHOT')
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ env.CURRENT_VERSION }}
          generateReleaseNotes: true
          commit: main
          prerelease: true
          body: |
            ## Download Instructions
            ### Maven
            ```xml
            <repository>
              <id>zugazagoitia-repo-snapshots</id>
              <name>Zugazagoitia Repository</name>
              <url>https://repo.zugazagoitia.com/snapshots</url>
            </repository>
            ```
            ```xml
            <dependency>
              <groupId>io.javalin</groupId>
              <artifactId>javalin-ssl</artifactId>
              <version>${{ env.CURRENT_VERSION }}</version>
            </dependency>
            ```
            ### Gradle
            ```groovy
            maven {
              url "https://repo.zugazagoitia.com/snapshots"
            }
            ```
            ```groovy
              implementation('io.javalin:javalin-ssl:${{ env.CURRENT_VERSION }}')
            ```

      - name: Create Release
        if: "!contains(env.CURRENT_VERSION, 'SNAPSHOT')"
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ env.CURRENT_VERSION }}
          generateReleaseNotes: true
          commit: main
          body: |
            ## Download Instructions
            ### Maven
            ```xml
            <repository>
              <id>zugazagoitia-repo-releases</id>
              <name>Zugazagoitia Repository</name>
              <url>https://repo.zugazagoitia.com/releases</url>
            </repository>
            ```
            ```xml
            <dependency>
              <groupId>io.javalin</groupId>
              <artifactId>javalin-ssl</artifactId>
              <version>${{ env.CURRENT_VERSION }}</version>
            </dependency>
            ```
            ### Gradle
            ```groovy
            maven {
              url "https://repo.zugazagoitia.com/releases"
            }
            ```
            ```groovy
              implementation('io.javalin:javalin-ssl:${{ env.CURRENT_VERSION }}')
            ```



