name: Test all JDKs on all OSes and Publish

on: [push]

permissions: write-all

jobs:
  
  coverage:
    runs-on: ubuntu-latest
    name: "📄 Codecov Report"
    strategy:
      matrix:
        test-type: [unit, integration]
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup and Run Gradle
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: ${{ matrix.test-type }}TestsCoverageReport
          
      - name: Ls coverage dir
        run: "ls -la ${{ github.workspace }}/build/reports/jacoco/${{ matrix.test-type }}TestsCoverageReport"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          files: "${{ github.workspace }}/build/reports/jacoco/${{ matrix.test-type }}TestsCoverageReport"
          flags: "${{ matrix.test-type }}Tests"
          verbose: true
          token: "${{ secrets.CODECOV_TOKEN }}"

